'use client'
// import type { Metadata } from "next";
import "./globals.css";
import { usePathname } from "next/navigation";
import Navbar from "./component/Navbar";

// export const metadata: Metadata = {
//   title: "یاد شهدای جاودان",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rout = usePathname()
  return (
    <html lang="en">
      <body dir="rtl">
        <div className="">
{rout != "/" &&(
  <Navbar/>
)}
          {children}
        </div>{" "}
      </body>
    </html>
  );
}
